### ISSUE TITLE
Research which DUO codes are compatible with MorPhiC

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/data-ingestion-development#26]
**Description of the issue**

For the usage of the DUO codes to display the availability of the data, we need to ensure that we are only allowing the values/data usage modifiers that are compatible with [CC by 4.0](https://creativecommons.org/licenses/by/4.0/)

**Tasks**

- [x] Create a document with all the current data usage restrictions/modifiers
- [x] Categorize each of the terms
- [x] Feedback w/ Tony and Gabs

**Comment by ESapenaVentura** [comment]
The document is provisionally here:

https://docs.google.com/spreadsheets/d/1NEe9A4Xq4iuhvsApWwcM5dfzO6V-qUsWcvmBi1ox5vY/edit#gid=0

I have read the legal code for CC by 4.0 to ensure I understand the specific cases and why or why not do they fit

I have only found the "no restrictions" to be compatible. The rest of the data usage modifiers have issues

**Comment by ESapenaVentura** [comment]
[DUOS assessment slides](https://docs.google.com/presentation/d/1rTqR7cMtOC5n3vUu53vdGYmJc72QHHW9Vk93vGD4aFM/edit#slide=id.g1e04d9ed1bf_0_1383)
